### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pstew** [TampaUseRs/TampaUseRs.github.io#1]
The link for 'We have a [discussion board](https://github.com/orgs/TampaUseRs/teams/everyone/discussions)...' gives a 404

**Comment by gadenbuie** [comment]
Hi @pstew -- The 404 error is GitHub's response when trying to access any page that requires authentication or permissions that a user currently doesn't have.

I invited you to join @TampaUseRs/everyone. When you accept and while logged in to GitHub you'll have access to the discussion board (not that there's a ton to see there but we welcome your questions/comments/etc!)

I'll make a note to update the language on the webpage to note that the discussion board is for @TampaUseRs org members.

**Comment by pstew** [comment]
Ah okay! I think I've only had experience with discussion boards on open projects. Thanks for clearing it up for me.

**Comment by gadenbuie** [comment]
No worries -- the 404 page is super confusing, but I guess it's best practice security-wise.
